CREATE TABLE SECURITY 
(
  EMPLOYEE_ID NUMBER(6,0) REFERENCES EMPLOYEES (EMPLOYEE_ID)
, SEC_ID VARCHAR2(20) 
, SEC_PASSWORD VARCHAR2(10) 
, SEC_STATUS CHAR(1) 
);

INSERT INTO "CJV805_202A09"."SECURITY" (EMPLOYEE_ID, SEC_ID, SEC_PASSWORD, SEC_STATUS) VALUES ('201', 'servlet', 'servlet', 'I')
INSERT INTO "CJV805_202A09"."SECURITY" (EMPLOYEE_ID, SEC_ID, SEC_PASSWORD, SEC_STATUS) VALUES ('202', 'java', 'java', 'I')
INSERT INTO "CJV805_202A09"."SECURITY" (EMPLOYEE_ID, SEC_ID, SEC_PASSWORD, SEC_STATUS) VALUES ('203', 'hr', 'hr', 'A')