CREATE OR REPLACE PACKAGE P_SECURITY AS
	TYPE cur_EmpInfo IS REF CURSOR;

	FUNCTION F_SECURITY(
		P_SECID IN SECURITY.SEC_ID%TYPE,
		P_SECPASSWORD IN SECURITY.SEC_PASSWORD%TYPE
	)
        RETURN NUMBER;

	PROCEDURE P_EMP_INFO (
		P_EMPLOYEEID IN EMPLOYEES.EMPLOYEE_ID%TYPE, 
		p_info OUT cur_EmpInfo
	);
END P_SECURITY; 

CREATE OR REPLACE PACKAGE BODY P_SECURITY AS
    FUNCTION F_SECURITY(
            P_SECID IN SECURITY.SEC_ID%TYPE,
            P_SECPASSWORD IN SECURITY.SEC_PASSWORD%TYPE
        )
            RETURN NUMBER
        IS
            EMPLOYEE_IDD NUMBER := 0 ;
    BEGIN 
        SELECT EMPLOYEE_ID INTO EMPLOYEE_IDD
                FROM SECURITY
                WHERE SEC_STATUS = 'A'
                    AND SEC_ID = P_SECID
                    AND SEC_PASSWORD = P_SECPASSWORD;
            
            RETURN EMPLOYEE_IDD;
            
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN 0 ;
    
    END F_SECURITY;
    
    PROCEDURE P_EMP_INFO (
		P_EMPLOYEEID IN EMPLOYEES.EMPLOYEE_ID%TYPE, 
		p_info OUT cur_EmpInfo
	) IS
    BEGIN
    OPEN p_info FOR
        SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = P_EMPLOYEEID;
    END P_EMP_INFO;
    
    
END P_SECURITY; 